[http]
host = "0.0.0.0"
port = 3000

[processor]
channel_capacity = 100

[validation.plugins]
SourceIdValidator = { allowed = [123] }
EventTypeValidator = { allowed = ["Heartbeat"] }

[processing.plugins]
StorageProcessor = {}
