[http]
host = "0.0.0.0"
port = 3000

[processor]
channel_capacity = 100

[validation.plugins]
SourceId = { allowed = [123] }
EventType = { allowed = ["Heartbeat"] }

[processing.plugins]
Storage = {}
